### ISSUE TITLE
Uncaught TypeError: Expected an object with 'start' and 'end' properties.

### ISSUE THREAD

**Issue by tiferrei** [lee-dohm/auto-copyright#21]
[Enter steps to reproduce:]

1. Try to insert copyright.

**Atom**: 1.19.0-beta3 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.13
**Thrown From**: [auto-copyright](https://github.com/lee-dohm/auto-copyright) package 0.5.0

### Stack Trace

Uncaught TypeError: Expected an object with 'start' and 'end' properties.

```
At /Users/tiferrei/.atom/packages/auto-copyright/lib/auto-copyright.coffee:34

TypeError: Expected an object with 'start' and 'end' properties.
    at AutoCopyright.hasCopyright (/packages/auto-copyright/lib/auto-copyright.coffee:34:29)
    at AutoCopyright.hasCopyright (/packages/auto-copyright/lib/auto-copyright.coffee:32:13)
    at AutoCopyright.hasCopyright (/packages/auto-copyright/lib/auto-copyright.coffee:32:13)
    at AutoCopyright.insertCopyright (/packages/auto-copyright/lib/auto-copyright.coffee:48:13)
    at Object.insert (/packages/auto-copyright/lib/main.coffee:37:12)
    at /packages/auto-copyright/lib/main.coffee:25:36)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom Beta.app/Contents/Resources/app/src/command-registry.js:265:35)
    at /Applications/Atom Beta.app/Contents/Resources/app/src/command-registry.js:3:65
    at Object.didConfirmSelection (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/command-palette/lib/command-palette-view.js:106:35)
    at SelectListView.confirmSelection (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/atom-select-list/src/select-list-view.js:313:26)
    at HTMLDivElement.core:confirm (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/atom-select-list/src/select-list-view.js:81:20)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom Beta.app/Contents/Resources/app/src/command-registry.js:265:35)
    at /Applications/Atom Beta.app/Contents/Resources/app/src/command-registry.js:3:65
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:610:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:401:28)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom Beta.app/Contents/Resources/app/src/window-event-handler.js:100:42)
    at HTMLDocument.<anonymous> (/Applications/Atom Beta.app/Contents/Resources/app/src/window-event-handler.js:3:65)
```

### Commands

```
     -5:28.1.0 settings-view:open (input.hidden-input)
     -5:12.6.0 core:move-to-top (input.hidden-input)
     -5:11.5.0 command-palette:toggle (input.hidden-input)
     -5:07.9.0 core:move-down (input.hidden-input)
     -5:07.8.0 core:confirm (input.hidden-input)
     -5:07.8.0 auto-copyright:insert (input.hidden-input)
     -4:19.2.0 settings-view:open (input.hidden-input)
     -2:35.3.0 editor:delete-to-beginning-of-line (input.hidden-input)
  4x -2:32.6.0 core:backspace (input.hidden-input)
     -2:00.9.0 command-palette:toggle (input.hidden-input)
  3x -1:58.4.0 core:move-down (input.hidden-input)
     -1:57.8.0 core:confirm (input.hidden-input)
     -1:57.8.0 auto-copyright:insert (input.hidden-input)
     -0:20.2.0 command-palette:toggle (input.hidden-input)
     -0:17.7.0 core:confirm (input.hidden-input)
     -0:17.7.0 auto-copyright:insert (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.30.3 
atom-material-syntax 1.0.6 
atom-material-ui 2.0.4 
auto-copyright 0.5.0 
autoclose-html 0.23.0 
autocomplete-clang 0.11.3 
autocomplete-cmake 0.3.1 
busy 0.7.0 
busy-signal 1.4.3 
color-picker 2.2.5 
dash-syntax 0.3.0 
dash-ui 0.4.0 
docker 0.7.0 
file-icons 2.1.8 
highlight-line 0.12.0 
intentions 1.1.2 
language-cmake 0.3.0 
language-docker 1.1.8 
language-ejs 0.4.0 
language-ini 1.19.0 
language-nginx 0.8.0 
language-swift 0.5.0 
linter 2.2.0 
linter-docker 0.2.0 
linter-gcc 0.7.1 
linter-jshint 3.1.5 
linter-ui-default 1.6.2 
markdown-writer 2.6.5 
platformio-ide-terminal 2.5.3 
print-code 0.7.0 
script 3.15.0 
tool-bar 1.1.0 
travis-ci-status 1.3.1 
```

config:
```
"auto-copyright":
    owner: "Tiago Ferreira"
    template: '''
      
      <FILENAME>
      <PROJECT NAME>
      
      Created by %o on DD/MM/%y.
      Copyright © %y %o
      
      THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
      IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
      FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
      AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
      WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
      CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
      
    '''
```

**Comment by thibault-martinez** [comment]
👍

**Comment by Olshansk** [comment]
Has this been resolved?

**Comment by StevenCopeland** [comment]
Not yet. I am still getting this error.

**Comment by chenillen** [comment]
any solutions?
