### ISSUE TITLE
Uncaught TypeError: Expected an object with 'start' and 'end' properties.

### ISSUE THREAD

**Issue by StevenCopeland** [lee-dohm/auto-copyright#22]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.19.0 x64
**Electron**: 1.6.9
**OS**: Ubuntu 16.04.3
**Thrown From**: [auto-copyright](https://github.com/lee-dohm/auto-copyright) package 0.5.0

### Stack Trace

Uncaught TypeError: Expected an object with 'start' and 'end' properties.

```
At /home/stevencopeland/.atom/packages/auto-copyright/lib/auto-copyright.coffee:34

TypeError: Expected an object with 'start' and 'end' properties.
    at AutoCopyright.hasCopyright (/packages/auto-copyright/lib/auto-copyright.coffee:34:29)
    at AutoCopyright.hasCopyright (/packages/auto-copyright/lib/auto-copyright.coffee:32:13)
    at AutoCopyright.hasCopyright (/packages/auto-copyright/lib/auto-copyright.coffee:32:13)
    at AutoCopyright.insertCopyright (/packages/auto-copyright/lib/auto-copyright.coffee:48:13)
    at Object.insert (/packages/auto-copyright/lib/main.coffee:37:12)
    at /packages/auto-copyright/lib/main.coffee:25:36)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app/src/command-registry.js:265:35)
    at CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app/src/command-registry.js:3:65)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/usr/share/atom/resources/app/src/command-registry.js:166:25)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (/usr/share/atom/resources/app/src/atom-environment.js:1338:34)
    at EventEmitter.outerCallback (/usr/share/atom/resources/app/src/application-delegate.js:334:31)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

### Commands

```
  2x -0:44.8.0 core:close (atom-pane.pane.active)
     -0:35.9.0 auto-copyright:insert (input.hidden-input)
```

### Non-Core Packages

```
atom-wrap-in-tag 0.6.0 
auto-copyright 0.5.0 
autoclose-html 0.23.0 
autocomplete-paths 2.6.0 
badges 2.2.5 
create-github-repo 1.1.2 
default-language 0.3.0 
jedit-syntax 0.2.0 
jedit-white-syntax 0.11.0 
montif-syntax 0.21.0 
sourcefetch-package 0.5.0 
wakatime 7.0.3 
```

**Comment by StevenCopeland** [comment]
Duplicate of #21
